### ISSUE TITLE
Adding Link to EncNet Repo

### ISSUE THREAD

**Issue by zhanghang1989** [junfu1115/DANet#1]
Great work! I found this project is based on EncNet / Encoding repository. Could you please consider adding a link to the EncNet Repo probably in the acknowledgement of the readme? I appreciate that.
https://github.com/zhanghang1989/PyTorch-Encoding

**Comment by junfu1115** [comment]
I will update the readme in the next few days. Thanks for your repository, especially the Synchronized BN!
