### ISSUE TITLE
PAM module consumes a lot of memory.

### ISSUE THREAD

**Issue by huang229** [junfu1115/DANet#104]
Thank you very much for your open source sharing. PAM is a very interesting module, but the memory consumption is also huge. I use resnet18, batch_size = 1, GPU consumes 1800MB, but after PAM module, it rises to 4000MB. What's the capacity of your GPU, and what's the size of your batch size?

**Comment by Dirtybluer** [comment]
I suppose you should check this:https://github.com/junfu1115/DANet/issues/58#issuecomment-489308463

**Comment by huang229** [comment]
@Dirtybluer Thank you! My 8g GPU can't play with this model. 
The shortcomings of PAM may just be the starting point for improvement.
