### ISSUE TITLE
您好~ 我借鉴了您的工作，我想咨询一下论文里的position attention 的可视化结果是怎么展示出来的呢。 

### ISSUE THREAD

**Issue by lvcat** [junfu1115/DANet#118]
阅读原文看方法好像是选择特征点，再输出特征点对应的attention图像？是直接使用attention模块还是在嵌入网络的情况下使用呢。请问有代码可以参照吗。  我比较菜问的可能比较简单 不好意思 == 。

**Comment by lvcat** [comment]
作者大大已经回复邮件 感恩

**Comment by Yufengevan** [comment]
我也想了解怎么实现可视化，方便交流一下吗

**Comment by shixiaopei** [comment]
> 我也想了解怎么实现可视化，方便交流一下吗

给我的邮箱发个邮件  2018232114@tju.edu.cn

**Comment by purse1996** [comment]
可以将这部分代码发给我一份吗 感谢 purse1996@gmail.com

**Comment by shixiaopei** [comment]
>

> 可以将这部分代码发给我一份吗 感谢 [purse1996@gmail.com](mailto:purse1996@gmail.com)

没有code  我发给你了思路  写好可以发我一份哈哈哈哈哈哈

**Comment by purse1996** [comment]
哈哈 好嘞，如果我写了的话！

shixiaopei <notifications@github.com> 于2020年10月14日周三 下午5:21写道：

**Comment by ming71** [comment]
> 作者大大已经回复邮件 感恩

请问能否分享一下可视化方法？我直接将通道和空间注意力可视化成热图的形式，但是没有论文这种效果。

**Comment by Carmenliang** [comment]
> 
> 
> > 我也想了解怎么实现可视化，方便交流一下吗
> 
> 给我的邮箱发个邮件 [2018232114@tju.edu.cn](mailto:2018232114@tju.edu.cn)

能给我发一份吗？谢谢！1051353427@qq.com

**Comment by Yeating** [comment]
你好，有可视化的代码分享吗？1042579084@qq.com

**Comment by sundongwei** [comment]
> 作者大大已经回复邮件 感恩

您好，希望能给发一份DANet可视化的代码。sundongwei@outlook.com

**Comment by Ben-lpj** [comment]
> > 作者大大已经回复邮件 感恩
> 
> 您好，希望能给发一份DANet可视化的代码。[sundongwei@outlook.com](mailto:sundongwei@outlook.com)



> > > 我也想了解怎么实现可视化，方便交流一下吗
> > 
> > 
> > 给我的邮箱发个邮件 [2018232114@tju.edu.cn](mailto:2018232114@tju.edu.cn)
> 
> 能给我发一份吗？谢谢！[1051353427@qq.com](mailto:1051353427@qq.com)

您好，请问方便了解一下如何可视化注意力图吗，我的邮箱是474655459@qq.com

**Comment by Eileen000** [comment]
可以将这部分代码发给我一份吗 感谢 1229589839@qq.com

**Comment by HengHeng-Yun** [comment]
您好，可以将可视化代码发我一份吗？ 非常感谢！ 18648610655@163.com

**Comment by DexiongZhang** [comment]
您好，请问方便了解一下如何可视化注意力图吗，我的邮箱是842716977@qq.com

**Comment by liguge** [comment]
> 您好，请问方便了解一下如何可视化注意力图吗，我的邮箱是[842716977@qq.com](mailto:842716977@qq.com)

请问可以发我一份吗？ 我的邮箱 huantaihechao@163.com

**Comment by linsy-ai** [comment]
您好可以将可视化代码发我一份吗？十分感谢！ 邮箱：810955019@qq.com

**Comment by He-Chao** [comment]
> 作者大大已经回复邮件 感恩

你好，请问这个channel attention map如何实现呢？方便分享一下吗1527981450@qq.com

**Comment by songyang86** [comment]
你好，请问这个channel attention map如何实现呢？方便分享一下吗1335496470@qq.com

**Comment by lvcat** [comment]
工作比较忙，没有空一一回复了，作者大大的回复如下：
相关的code当时没有整理，之后有同学问我，我整理了一下步骤如下，你可以按照步骤大体实现一下
1 Get attention feature from PAM/CAM, you should modify forward code(models/base.py) (feed the whole image to a network)
2 Modify test.py to save attention feature(（using np.save(XXX.npy)）),shape is BxNxN 
3 For PAM, we decode the saved attention feature (using np.load(XXX.npy)), each row is an attention map for the corresponding pixel, 
then, you can resize img (2048*1020) to (256*128) and get pixel index form image(x,y value), where you need (like one pixel from a person or a car ), the row of the pixel of attention is M = W * y + x, attention[:,M:M+1,:] is Mth attention map for the corresponding pixel.
4 For CAM, when u save the feature map(before/after apply CAM), then  u can use opencv(function:  applyColorMap) to visualize.


> 你好，请问这个channel attention map如何实现呢？方便分享一下吗[1335496470@qq.com](mailto:1335496470@qq.com)

**Comment by MiaoRain** [comment]
请问有把可视化代码实现的吗？麻烦分享一下，非常感谢260599780@qq.com

**Comment by Carl12138aka** [comment]
感恩的心，求好心人转发我一份，1512844159@qq.com

**Comment by zhunzhun123** [comment]
您好，请问方便了解一下如何可视化注意力图吗，谢谢您好心人！我的邮箱是：1040363502@qq.com

**Comment by xxhaonan** [comment]
您好，希望能给发一份DANet可视化的代码。非常感谢！我的邮箱是:xihaonancn@gmail.com
