### ISSUE TITLE
Connection Error when downloading Pascal Dataset

### ISSUE THREAD

**Issue by HieuPhan33** [junfu1115/DANet#134]
Hi, I use the script prepare_pcontext.py to download Pascal context data, but I got connection error:
```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='host.robots.ox.ac.uk', port=80): Max retries exceeded with url: /pascal/VOC/voc2010/VOCtrainval_03-May-2010.tar (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff94ad30100>: Failed to establish a new connection: [Errno 113] No route to host'))
```
I have checked the firewall or border authentication, they are all open.

I can download other datasets, such as Cityscapes, COCO, ADE20k. But I failed to download Pascal VOC and Pascal Context.

Appreciate your help.

**Comment by wlj567** [comment]
Hello, have you passed the complete code? Is it convenient to add a contact information? Thank you!

**Comment by HieuPhan33** [comment]
Hello, the pascal voc server was down at that time. Now the server is working.

**Comment by wlj567** [comment]
Ok.
