### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'log_softmax'`

### ISSUE THREAD

**Issue by wlj567** [junfu1115/DANet#142]
> Traceback (most recent call last):
> File "/home/pxg/DAN/DANet/experiments/segmentation/train.py", line 282, in
trainer.training(epoch)
> File "/home/pxg/DAN/DANet/experiments/segmentation/train.py", line 214, in training
loss = self.criterion(outputs, target)
> File "/home/pxg/DAN/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
> File "/home/pxg/DAN/DANet/encoding/parallel.py", line 130, in forward
return self.module(inputs, *targets[0], **kwargs[0])
> File "/home/pxg/DAN/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
> File "/home/pxg/DAN/DANet/encoding/nn/loss.py", line 68, in forward
return super(SegmentationLosses, self).forward(*inputs)
> File"/home/pxg/DAN/venv/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 904, in forward
ignore_index=self.ignore_index, reduction=self.reduction)
> File "/home/pxg/DAN/venv/lib/python3.6/site-packages/torch/nn/functional.py", line 1970, in cross_entropy
return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
> File "/home/pxg/DAN/venv/lib/python3.6/site-packages/torch/nn/functional.py", line 1295, in log_softmax
ret = input.log_softmax(dim)
> AttributeError: 'tuple' object has no attribute 'log_softmax'`
Hello, can you help me see what the problem is?

**Comment by shinkusuki** [comment]
Can you solve this problem? I meet the similar one. Thank you!

**Comment by wlj567** [comment]
Sorry, I didn't solve the problem.
