### ISSUE TITLE
How large GPU memory you used?

### ISSUE THREAD

**Issue by karenyun** [junfu1115/DANet#18]
Hi, @junfu1115 thanks for your work!
I am curious about the GPU memory you used, since the attention will introduce many parameters and the image size of cityscape is very large 2048*1024, I found you resize the image to a base size 608, is the 12GP memory enough for that?

**Comment by tianhaijie** [comment]
Sorry for the late respond.  For cityscapes datasets,we set base size 1024 and crop size 768, the code needs about 15GB for training.

**Comment by karenyun** [comment]
Thanks very much!
I also try to use the attention for segmentation, I find it also influences the training speed if the attention scale is much large. Do you have any suggestions for the speed?
