### ISSUE TITLE
About the Multi-grid Parts

### ISSUE THREAD

**Issue by PkuRainBow** [junfu1115/DANet#2]
Interesting work. We also have a concurrent work [OCNet](https://github.com/PkuRainBow/OCNet).

In fact, we used to have tried the multi-grid method but find it brings no performance gains.

Thus I am wondering whether you only use multi-grid for only **testing** or **both training and testing**?

**Comment by junfu1115** [comment]
Both. I adopt the multi-grid method following deeplabv3!

**Comment by lzrobots** [comment]
it seems you used multi-grid by following psp rather than deeplabv3?
can you confirm? thanks

**Comment by lzrobots** [comment]
@junfu1115 any thought?
