### ISSUE TITLE
Training setting for cocostuff?

### ISSUE THREAD

**Issue by zhijiew** [junfu1115/DANet#20]
Hi! Thank you for your great work!  Could you please tell me the settings of cocostuff10k to reproduce your results? (like base-size, crop-size, epochs, batch-size, lr and multi-dilation, etc.)

Thanks again!

**Comment by junfu1115** [comment]
the same as pascal context dataset, you can refer to the experimental settings of  [PyTorch-Encoding](https://github.com/zhanghang1989/PyTorch-Encoding)
