### ISSUE TITLE
The value of self.gamma

### ISSUE THREAD

**Issue by rinawhale** [junfu1115/DANet#22]
**Hi, when the gamma is initialized to 0, how does it become other values. I know it's a parameter that can be changed after learning, but I don't understand how it changed. I am confused, because i think its value is always 0.**

**Comment by chenyzh28** [comment]
I found the value is still very small after the training process.

**Comment by XiaLiPKU** [comment]
> 
> 
> I found the value is still very small after the training process.

And I just wonder why not initialize it as 1. Which is more suitable, at least in my mind

**Comment by Raazzta** [comment]
@chenyzh28 negative or positive value?
