### ISSUE TITLE
how to insert DANet module to other backbone network?

### ISSUE THREAD

**Issue by osakaka** [junfu1115/DANet#28]
@junfu1115   
I want to apply danet module to deeplab, so i am not sure how to insert it, wheater the front/middle/end of backbone(xception),or before ASPP module and behind ASPP, can you help me?

**Comment by tianhaijie** [comment]
Y can apply danet module at the end of backbone. If u want to use both aspp and danet, u can try to apply danet before or behind aspp, since we dont try aspp in our network, i can not give u a clear answer.
