### ISSUE TITLE
I found a error in SegmentationMultiLosses forward function

### ISSUE THREAD

**Issue by xiongzhanblake** [junfu1115/DANet#29]
Hi, 
I found a error in SegmentationMultiLosses's forward function at https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/encoding/nn/customize.py#L100
'*preds' is the correct variable instead of 'preds'. Otherwise, it pops up an error like:
"ValueError: not enough values to unpack (expected 3, got 1)"

Cheers!

**Comment by tianhaijie** [comment]
In our code, we use three loss(one main loss + two auxi loss).This error seems that u only return one loss. Have u modified the code in forwrad?

**Comment by xiongzhanblake** [comment]
No. I did not change the code in forward.

**Comment by yiqigo0215** [comment]
I also have encountered this error, how to fix it
