### ISSUE TITLE
Reproducing Cityscapes

### ISSUE THREAD

**Issue by erikgaas** [junfu1115/DANet#30]
Running the command supplied by the repo, 

``` CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset cityscapes --model  danet --backbone resnet101 --checkname danet101  --base-size 1024 --crop-size 768 --epochs 240 --batch-size 8 --lr 0.003 --workers 2 --multi-grid --multi-dilation 4 8 16```

returned a mIOU of 0.735 at the end of 240 epochs. There is probably some randomness in running through the dataset, but I'm surprised it was that much lower than anticipated. Any advice on how to get closer to reported scores?

**Comment by XiaLiPKU** [comment]
I find this sentence in the paper: "The  base  learning  rate  is  set  to  0.01 for Cityscapes dataset and 0.001 for others. " But in the repo, the lr is recommended as 0.03. So I'm also confused as you. Looking forward the reply from the author.

> 
> 
> Running the command supplied by the repo,
> 
> ` CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset cityscapes --model danet --backbone resnet101 --checkname danet101 --base-size 1024 --crop-size 768 --epochs 240 --batch-size 8 --lr 0.003 --workers 2 --multi-grid --multi-dilation 4 8 16`
> 
> returned a mIOU of 0.735 at the end of 240 epochs. There is probably some randomness in running through the dataset, but I'm surprised it was that much lower than anticipated. Any advice on how to get closer to reported scores?

**Comment by junfu1115** [comment]
When training, the results is not the real mIoU, you need run test.py to obtain real mIoU,  In addition, we 
training FCN, and DANet(only PAM/CAM) with one loss, the lr is set to 0.01, And we adopted three loss(one main loss + two auxi loss) in DANet(PAM+CAM), we adopt 0.003 as final lr. @XiaLiPKU

**Comment by LiuPearl1** [comment]
@junfu1115 Why training stage mIoU results is not real? Can you explain about this? Thank you.

**Comment by EmmaW8** [comment]
@LiuPearl1 I think it may because the images for test are from val dataset. But the results reported from test dataset.

**Comment by junfu1115** [comment]
@LiuPearl1 In training phase, we evalute the model with only a part of image, while whole  image in test phase.

**Comment by LiuPearl1** [comment]
> @LiuPearl1 In training phase, we evalute the model with only a part of image, while whole image in test phase.

Thank you. I get it.

**Comment by lyn-rgb** [comment]
> Running the command supplied by the repo,
> 
> ` CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --dataset cityscapes --model danet --backbone resnet101 --checkname danet101 --base-size 1024 --crop-size 768 --epochs 240 --batch-size 8 --lr 0.003 --workers 2 --multi-grid --multi-dilation 4 8 16`
> 
> returned a mIOU of 0.735 at the end of 240 epochs. There is probably some randomness in running through the dataset, but I'm surprised it was that much lower than anticipated. Any advice on how to get closer to reported scores?
@erikgaas 
Have you reproduced the result？
