### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by FENGShuanglang** [junfu1115/DANet#32]
![image](https://user-images.githubusercontent.com/38462831/49987843-c7b9c380-ffaf-11e8-9368-450ae01b1ee7.png)
https://github.com/rishizek/tensorflow-deeplab-v3/blob/a5d7ff2a14ebafb8a9b783271e4add82488528d3/utils/preprocessing.py#L115,this is deeplabv3,
![image](https://user-images.githubusercontent.com/38462831/49987989-431b7500-ffb0-11e8-8796-811aabfbd14a.png)

but i can't find any opt in your code about training with random scaling!Am I getting it wrong?thanks a lot

**Comment by lxtGH** [comment]
I got the same question with you

**Comment by junfu1115** [comment]
Here. https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/encoding/datasets/base.py#L77
