### ISSUE TITLE
training on single gpu

### ISSUE THREAD

**Issue by yiqigo0215** [junfu1115/DANet#33]

**Comment by yiqigo0215** [comment]
I have changed norm_layer=torch.nn.BatchNorm2d,self.model = self.model.cuda(), self.criterion = self.criterion.cuda(). While trying to train the network I encountered this error, site-packages/encoding/nn/customize.py", line 103, in forward
pred1, pred2 ,pred3= tuple(preds)
ValueError: not enough values to unpack (expected 3, got 1)

**Comment by yiqigo0215** [comment]
@huanghoujing

**Comment by huanghoujing** [comment]
@yiqigo0215 It seems that you have modified the contents of `SegmentationMultiLosses`. The original is [this](https://github.com/junfu1115/DANet/blob/201d308581d9d5a780a99f425eb5aee53bf3680b/encoding/nn/customize.py#L90), as shown below.
```python
class SegmentationMultiLosses(CrossEntropyLoss):
    """2D Cross Entropy Loss with Multi-L1oss"""
    def __init__(self, nclass=-1, weight=None,size_average=True, ignore_index=-1):
        super(SegmentationMultiLosses, self).__init__(weight, size_average, ignore_index)
        self.nclass = nclass


    def forward(self, *inputs):

        *preds, target = tuple(inputs)
        pred1, pred2 ,pred3= tuple(preds)


        loss1 = super(SegmentationMultiLosses, self).forward(pred1, target)
        loss2 = super(SegmentationMultiLosses, self).forward(pred2, target)
        loss3 = super(SegmentationMultiLosses, self).forward(pred3, target)
        loss = loss1 + loss2 + loss3
        return loss
```
Can you post your version here?

**Comment by InstantWindy** [comment]
> I have changed norm_layer=torch.nn.BatchNorm2d,self.model = self.model.cuda(), self.criterion = self.criterion.cuda(). While trying to train the network I encountered this error, site-packages/encoding/nn/customize.py", line 103, in forward
> pred1, pred2 ,pred3= tuple(preds)
> ValueError: not enough values to unpack (expected 3, got 1)

Hi. Can you train it with one GPU?
