### ISSUE TITLE
`t >= 0 && t < n_classes`

### ISSUE THREAD

**Issue by yiqigo0215** [junfu1115/DANet#35]
I use my dataset which has 81 catg，when train the model, error like:
      /pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [1,0,0], thread: [246,0,0] Assertion `t >= 0 && t < n_classes` failed.

**Comment by junfu1115** [comment]
Maybe you need modify the number (ignore label is set to 255 on cityscapes) in https://github.com/junfu1115/DANet/blob/042693afa7a7a3794ee4e2ec92c676ef97e9c713/encoding/datasets/base.py#L98

**Comment by LiuPearl1** [comment]
@junfu1115 I wonder for ade20k, where to change for `/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:99: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [6,0,0], thread: [1023,0,0] Assertion `t >= 0 && t < n_classes` failed.` problems. Should I change `fill=255` to `fill=0`?
