### ISSUE TITLE
Visualization of the attention map.

### ISSUE THREAD

**Issue by HqWei** [junfu1115/DANet#36]
Nice jobs! Do you mind to provide the code or details about how to implement the visualization of the attention map?

**Comment by junfu1115** [comment]
You can email to me.

**Comment by HqWei** [comment]
Is jun.fu@nlpr.ia.ac.cn right?

**Comment by qiulesun** [comment]
@HqWei @junfu1115 Could you tell me how to visualize attention map? My e-mail is qiulesun@mail.dlut.edu.cn.

**Comment by FibonacciZ** [comment]
Have you got the code? Would you mind sending me the code.Thank you in advance.  Email 523759909@qq.com
