### ISSUE TITLE
why the learned position attention map highlights regions of the same class as the query pixel

### ISSUE THREAD

**Issue by yaoqi-zd** [junfu1115/DANet#40]
Hi, May I ask why the learned position attention map highlights regions of the same class as the query pixel ? if it's because each pixel is imposed with label supervision to make pixels from same class share similar feature, then why do we need to harvest feature from other pixels of the same class?

**Comment by junfu1115** [comment]
I think it could enhance  intra-class compactness on which softmaxloss has not focused

**Comment by yaoqi-zd** [comment]
so you think it is because under pixel-level supervision, pixels of the same class shares similar feature, so the position attention map would highlight regions of the same class as the query pixel ?

**Comment by junfu1115** [comment]
@yaoqi-zd You could say that
