### ISSUE TITLE
Which crop_size did you  adopt in your ablation experiments on Cityscapes, 768 or 1024?  

### ISSUE THREAD

**Issue by yougoforward** [junfu1115/DANet#42]
Since we usually test with the full size, I am a little confused  with  scripts you provided for single scale testing and multi-scale testing, in which the crop_size are 768 and 1024. Then which crop_size did you use in ablation study  in your paper on Cityscapes dataset , 768 or 1024?

**Comment by junfu1115** [comment]
@yougoforward, I adopt sliding window to test our model, 768 is used to in ablation study. In addition, we find that using larger crop size benefit for testing, we adopt 1024 during multi-scale testing phase.

**Comment by yougoforward** [comment]
@junfu1115 Thank you very much!
