### ISSUE TITLE
why center crop for testing instead of the whole image?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [junfu1115/DANet#44]
hi @junfu1115 
i have a question: in `BaseDataset`, the func `_val_sync_transform` use `center-crop` to crop the image. is it reasonable to use `center-crop` to test the model instead of the whole image?
thanks.

**Comment by junfu1115** [comment]
@zimenglan-sysu-512 you can ref https://github.com/zhanghang1989/PyTorch-Encoding/issues/127#issuecomment-427913523  and we adopt test.py  to obtain final result

**Comment by zimenglan-sysu-512** [comment]
hi @junfu1115 
in `danet/test.py`, it seems that u don't set any params for `base_size` and `crop_size`, and still use `_val_sync_transform` to process the image. 
can u show some details how do u process the image and mask when u test?

**Comment by Mr-zihao** [comment]
@zhiweifang he uses the whole image without sync_transform when testing

**Comment by zimenglan-sysu-512** [comment]
hi @Mr-zihao 
can u show me the code? i can't find them. thanks.

**Comment by Mr-zihao** [comment]
@zimenglan-sysu-512 in test.py, the mode of get_dataset_model is testval with which the images only are transformed into tensor without crop、flip etc...

**Comment by Mr-zihao** [comment]
@zimenglan-sysu-512 And if you get the same result as the paper,please tell me,thanks,there are some troubles with me.

**Comment by zimenglan-sysu-512** [comment]
@Mr-zihao 
u are right, i ignore this details. thanks
