### ISSUE TITLE
'Ninja is required to load C++ extensions'

### ISSUE THREAD

**Issue by Kobeee0614** [junfu1115/DANet#46]
`Ninja is required to load C++ extensions`
Can you tell me what to do?

**Comment by qk8937599** [comment]
Maybe you should install pytorch from source and the install torch-encoding

**Comment by EmmaW8** [comment]
I installed ninja by `conda install ninja`.
But encounter another problem:
Traceback (most recent call last):
  File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 739, in _build_extension_module
    ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
  File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by LiuPearl1** [comment]
@EmmaW8 May you should install `ninja` in your system environment rather than virtual environment.

**Comment by Manuscript1024** [comment]
I try to solve the issue by using "pip3 install ninja" ,but it dosen't seem work!.I meet the problem yet.

**Comment by Dirtybluer** [comment]
> I installed ninja by
> `conda install ninja`.
> 
> But encounter another problem:
> Traceback (most recent call last):
> File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 739, in _build_extension_module
> ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
> File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
> **kwargs).stdout
> File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/subprocess.py", line 418, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I met the same problem. Have you solved it yet?

**Comment by Dirtybluer** [comment]
> I installed ninja by
> `conda install ninja`.
> 
> But encounter another problem:
> Traceback (most recent call last):
> File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 739, in _build_extension_module
> ['ninja', '-v'], stderr=subprocess.STDOUT, cwd=build_directory)
> File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
> **kwargs).stdout
> File "/data/ssd/public/lzhu/anaconda3/lib/python3.6/subprocess.py", line 418, in run
> output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

I met the same problem, have you solved it yet?

**Comment by Dirtybluer** [comment]
> @EmmaW8 May you should install `ninja` in your system environment rather than virtual environment.

How dose that make sense?
