### ISSUE TITLE
convert Cityscapes dataset to 19 categories.

### ISSUE THREAD

**Issue by qiulesun** [junfu1115/DANet#47]
It's the wonderful work.
For the section Dataset of Usage in readme file,  you mention that 

1. Download the Cityscapes dataset and convert the dataset to 19 categories.

Here, why do we first convert Cityscapes dataset to 19 categories rather than directly using the original one?
The question maybe too simple and I'm still looking forword to your replying if you have enough time.

**Comment by junfu1115** [comment]
@qiulesun Thanks, the dataset provides 30 class labels, while most methods adopt 19 classes to evaluate their method, We didn't use the original one.

**Comment by TianMingChen** [comment]
> @qiulesun Thanks, the dataset provides 30 class labels, while most methods adopt 19 classes to evaluate their method. In order to compare with other methods, we adopt 19 classes and don't try the original one.

![image](https://user-images.githubusercontent.com/20785298/56499056-3e0a9b80-6537-11e9-8ce7-feab6ba3ee7f.png)
when i convert Cityscapes dataset to 19 categories,how should I to solve this problem?
