### ISSUE TITLE
About the `Softmax` in the `CAM_Module`

### ISSUE THREAD

**Issue by lartpang** [junfu1115/DANet#48]
https://github.com/junfu1115/DANet/blob/799424e7fd9efa5723038ad0dc27c46682160e57/encoding/nn/attention.py#L75

![image](https://user-images.githubusercontent.com/26847524/55683213-e46b7400-596f-11e9-969e-800ed03076b5.png)

Is your code trying to improve numerical stability? Maybe it should be in this form.

```python
       energy_new = torch.max(energy, -1, keepdim=True)
       energy_new = energy_new[0].expand_as(energy)
       energy_new = energy - energy_new
       attention = self.softmax(energy_new)
```

**Comment by junfu1115** [comment]
@lartpang Thanks, we have tried the form you provide, but the performance is not good

**Comment by lartpang** [comment]
Well, can I take it as a practical experience?

**Comment by junfu1115** [comment]
@lartpang This might be an attempt, in other cases,

**Comment by lartpang** [comment]
OK, thanks for your answer and your code... 

This idea is so good, except for some extra memory... It's more suitable for a position where the number of channels is small.

**Comment by junfu1115** [comment]
@lartpang Thanks
