### ISSUE TITLE
Why the size of x is B X C X W X H?

### ISSUE THREAD

**Issue by chenwydj** [junfu1115/DANet#5]
I wonder why the size of x is B X C X W X H? Although it doesn't affect the calculation.

here:
https://github.com/junfu1115/DANet/blob/664e98d425c1cd00f0bc087a208abe2913a885d3/encoding/nn/attention.py#L42

and also in the comments:
https://github.com/junfu1115/DANet/blob/664e98d425c1cd00f0bc087a208abe2913a885d3/encoding/nn/attention.py#L37

Thank you!

**Comment by junfu1115** [comment]
We updated the code to B X C X H X W
