### ISSUE TITLE
trained model DANet is damaged.

### ISSUE THREAD

**Issue by zxy77** [junfu1115/DANet#54]
After the download of the compressed package is completed, it cannot be decompressed, and the file is damaged. Can it be re-uploaded please?

**Comment by zrl4836** [comment]
删除后缀.tar就可以了

**Comment by hgmlu** [comment]
> 删除后缀.tar就可以了

你好，我在下载预训练模型的过程中遇到了些问题，请问方便发一份给我吗？
我的邮箱：hgm_1107@163.com
