### ISSUE TITLE
About the `Conv-BatchNorm-ReLU` in PaperV3 & PaperV4

### ISSUE THREAD

**Issue by LarT2P** [junfu1115/DANet#61]
I know there is a similiar question: https://github.com/junfu1115/DANet/issues/45

But I would like to know  if there is a big impact on the effect of this module.

Thx!

---

* PaperV3 https://arxiv.org/pdf/1809.02983v3.pdf
![image](https://user-images.githubusercontent.com/16298490/56843962-c47a0100-68da-11e9-8280-76ce80ad1508.png)

* PaperV4https://arxiv.org/pdf/1809.02983.pdf
![image](https://user-images.githubusercontent.com/16298490/56843957-baf09900-68da-11e9-836e-6d9c955f007a.png)

**Comment by junfu1115** [comment]
@LarT2P Sorry for the  inconsistent statement in paperv3, we correct the statement in paperv4. I haven't tried the experiments with BN and Relu.

**Comment by LarT2P** [comment]
OK, thanks for your reply...
