### ISSUE TITLE
A question about PAM_Module

### ISSUE THREAD

**Issue by chen048738** [junfu1115/DANet#64]
in PAM_Module forward :

out = torch.bmm(proj_value, attention.permute(0, 2, 1))

why atttention( B X (HxW) X (HxW) ) need permute(0, 2, 1)?

**Comment by WangboML** [comment]
I think it was a error, permute(0, 2, 1) should remove

**Comment by Raazzta** [comment]
@WangboML , if not permute then it will be differrent with what paper say, right?
