### ISSUE TITLE
How should I modify coco.py to train on COCO Stuff dataset?

### ISSUE THREAD

**Issue by RyanHTR** [junfu1115/DANet#65]
Hi, it's a nice work and I'm going to reproduce the paper's result on COCO Stuff dataset. Could you tell me is there any thing to change in encodingdataset/coco.py to make it compatible to load COCO Stuff dataset? And do you use the cocostuff-10k-v1.0 dataset for training?

**Comment by Anikily** [comment]
Hi,have you solved this problem?

**Comment by Anikily** [comment]
@RyanHTR
