### ISSUE TITLE
I am curious about how image with scale 2.2 times than origin image could be sent to model

### ISSUE THREAD

**Issue by shoutOutYangJie** [junfu1115/DANet#68]
I have a RTX2080Ti with 11G memory, but i still get error of OUT of memory when i input a large image, what strategy do you use to deal with this problem? Thanks your for this great work!!!

**Comment by HolmesShuan** [comment]
FYI. TiTan Xp with 12G memory or RTX2080Ti with FP16 training.

**Comment by shoutOutYangJie** [comment]
> FYI. TiTan Xp with 12G memory or RTX2080Ti with FP16 training.

hello, what does ''FP16" mean?

**Comment by HolmesShuan** [comment]
16-bit Floating-Point operations.
[https://devblogs.nvidia.com/apex-pytorch-easy-mixed-precision-training/](https://devblogs.nvidia.com/apex-pytorch-easy-mixed-precision-training/)
[https://discuss.pytorch.org/t/training-with-half-precision/11815](https://discuss.pytorch.org/t/training-with-half-precision/11815)
[https://hackernoon.com/rtx-2080ti-vs-gtx-1080ti-fastai-mixed-precision-training-comparisons-on-cifar-100-761d8f615d7f](https://hackernoon.com/rtx-2080ti-vs-gtx-1080ti-fastai-mixed-precision-training-comparisons-on-cifar-100-761d8f615d7f)
