### ISSUE TITLE
how to Visualize results of attention modules on Cityscapes val set

### ISSUE THREAD

**Issue by 1451154** [junfu1115/DANet#74]
hello, can you tell me how to Visualize results of attention modules on Cityscapes val set?

**Comment by BroHUAJI** [comment]
Have you solved this problem?

**Comment by qiulesun** [comment]
@1451154 @BroHUAJI @junfu1115 I do want to how to visualize attention map. Could you provide any idea to achive that?

**Comment by Yufengevan** [comment]
> Have you solved this problem?
Have you solved this problem?
