### ISSUE TITLE
SegmentationMultiLosses

### ISSUE THREAD

**Issue by Bodhi-robbery** [junfu1115/DANet#79]
hi， i met this question 
      Traceback (most recent call last):
  File "train.py", line 23, in <module>
    from encoding.nn import SegmentationMultiLosses
ImportError: cannot import name 'SegmentationMultiLosses'

 so ,what should i do can solve this problem.thanks very much.

**Comment by llypeony** [comment]
You should run 'python setup.py install' to install the encoding module.

**Comment by Bodhi-robbery** [comment]
sorry，i had did it.but now i didn't train,so maybe what reason?could you explain that?



---Original---
