### ISSUE TITLE
I can't download trained model! Can you help me ?

### ISSUE THREAD

**Issue by BroHUAJI** [junfu1115/DANet#81]
I can't download the trained model from the link you provided. Can you provide some other links? Such as Baidu Cloud. THANKS!!

**Comment by QTJiebin** [comment]
The file DANet101.pth.tar downloaded from the given link can not be uncompressed successful...

**Comment by hgmlu** [comment]
I met the same problem,have you solved it?

**Comment by stdmkmehp** [comment]
> The file DANet101.pth.tar downloaded from the given link can not be uncompressed successful...

Hello.
I'm blocked to download the file. 
Could I get a copy from you? My email is 1628284520@qq.com.
I would appreciate it very much if you can give me a hand.
