### ISSUE TITLE
The pretrained model can not be uncompressed successfully

### ISSUE THREAD

**Issue by QTJiebin** [junfu1115/DANet#85]
Dear authors, I find that the file DANet101.pth.tar downloaded from the given link can not be uncompressed successful. Waiting for your help, thx.

**Comment by VincentXWD** [comment]
You shouldn't decompress this model file because the model is not compressed though its extname is .tar

**Comment by player1321** [comment]
@QTJiebin Found the same bug, how did you solve this?
