### ISSUE TITLE
Does these 1x1 convs' input channel should be a const value?

### ISSUE THREAD

**Issue by VincentXWD** [junfu1115/DANet#88]
Have a question here:
https://github.com/junfu1115/DANet/blob/master/encoding/models/danet.py#L79-L82

What I wonder is that does these 1x1 convs' input channel should be a const value? I think set all 1x1 convs' input channel to 'inter_channels' rather than '512' should be better.

If it's not better nor it's not consistant with the paper, please point it out. Thanks.

**Comment by VincentXWD** [comment]
@junfu1115

**Comment by junfu1115** [comment]
Thanks.
