### ISSUE TITLE
why feature matmul can metric the feature similarity

### ISSUE THREAD

**Issue by hust-kevin** [junfu1115/DANet#90]
In non-local network or in DANet both use a matrix S which shape is `N*N and N=H*W` to show the similarity of two feature,  my question is why matmul can  metric the feature similarity? for example there are feature `f1=[1,1,1], f2=[1,1,1],f3=[1,2,3], and f1*f2=3, f1*f3=6`, the result between is f1 and f3 is larger f1 and f2, but we can know f1 and f2 are the same feature, so they are more similarity

**Comment by huang229** [comment]
@hust-kevin You can see the reason by looking at PCA.
