### ISSUE TITLE
is it necessary to install pytorch from sourcecode? 

### ISSUE THREAD

**Issue by seasonyang** [junfu1115/DANet#91]

**Comment by Angus-Lee** [comment]
Not necessary. But make sure your pytorch version is 0.4. Just
conda install pytorch=0.4.1 cuda90 -c pytorch

**Comment by Stephanessy** [comment]
@Angus-Lee Which version of python and cuda should I install? Could you specify your environment in detail if possible?

**Comment by sonaalPradeep** [comment]
@Angus-Lee This doesn't seem to work for me. I'm getting the following error...

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                  

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
.
.
.



An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
