### ISSUE TITLE
This is a very good job. Thank you for sharing.

### ISSUE THREAD

**Issue by huang229** [junfu1115/DANet#95]
This is a very good job. Thank you for sharing.
You have a good grasp of the principle of PCA. Whether it's a PAM or a CAM module, it's a great idea. The matrix correlation principle is used to learn the correlation between each channel and each point, which well combines the traditional algorithm with the deep learning. admire!!!

**Comment by bluesky314** [comment]
Can you explain abit more in depth how these things are related to PCA? I am thinking more from attention framework as finding the relation between spatial and channel regions.

**Comment by huang229** [comment]
@bluesky314  I was learning traditional algorithms. This is only my personal point of view, only for reference.You may need to look at some traditional algorithms. For example, matrix correlation or correlation between two distributions. PCA only uses a well-known algorithm of matrix correlation.
