### ISSUE TITLE
很多问题啊， 感觉代码很多兼容性问题  现在高版本的pytorch不行，

### ISSUE THREAD

**Issue by XUYUNYUN666** [junfu1115/DANet#98]
![image](https://user-images.githubusercontent.com/38391161/71157167-6b514a00-227c-11ea-9ee9-e9e78e582e9a.png)

**Comment by luckieucas** [comment]
你好，请问你编译通过了吗？

**Comment by yanchangqin** [comment]
请问你解决了吗

**Comment by HappyFee** [comment]
python setup.py install

**Comment by joker5743** [comment]
1.1.0版本的pytorch，按照这位朋友的经历：https://zhuanlan.zhihu.com/p/53418563，改了第一步（我是把-v改成我的-version而不是--v），之后卡在了第二步。没法编译，感觉这个是0.4的版本，1.x以后的版本API改动很大不适合了。
